QX only opened a qasm file, this closes it.
QuTech-Delft/qx-simulator pull request #93
Opened 2021-07-02 12:18 UTC by anneriet

I kept getting a "too many open files" error when running qxelerator tests, so I took a look into the source code and found out that the qasm files weren't being closed. This should fix that, my tests don't give the error anymore and the open qasm file is not used after parsing anyway.

2022-01-20 16:02 UTC, QFer requested changes

2022-01-20 16:02 UTC, QFer commented on include/qx/simulator.h
> +    std::string file_path;
This one should be private also

2022-01-20 16:02 UTC, QFer commented on include/qx/simulator.h
> +            fclose (qasm_file);
file is not closed when compiler::QasmSemanticChecker throws an exception

2022-09-26 07:59 UTC, pablolh commented
I fixed it too in https://github.com/QuTech-Delft/qx-simulator/pull/96

2022-10-20 08:55 UTC, jvansomeren commented
There are unresolved comment from Fer and some request to Anneriet.

2022-10-20 11:11 UTC, closed without merging